# Generated by Django 5.0.2 on 2024-03-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('link', models.URLField()),
            ],
        ),
    ]
